!obj:pylearn2.train.Train {
    dataset: &train !obj:friesnsteaks.datasets.food100.FOOD100 {
        which_set: 'train',
        input_size: %(input_size)i,
        axes: %(axes)s
    },
    model: !obj:pylearn2.models.mlp.MLP {
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [%(input_size)i, %(input_size)i],
            num_channels: 3,
            axes: %(axes)s
        },
        layers: [ 
                 !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h2',
                     output_channels: %(input_size)i,
                     irange: .05,
                     kernel_shape: [10, 10],
                     pool_shape: [10, 10],
                     pool_stride: [2, 2],
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     irange: .01,
                     n_classes: 74, 
                     layer_name: 'y'
                 }
            ],
    },
    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
        batch_size: 500,
        line_search_mode: 'exhaustive',
        monitoring_dataset:
            {
                'train' : *train,
                'test'  : !obj:friesnsteaks.datasets.food100.FOOD100 {
                              which_set: 'test',
                              input_size: %(input_size)i,
                              axes: %(axes)s
                          }
            },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 50 
                },
            ]
        },
    },
    extensions: [ 
       !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
           channel_name: 'test_y_misclass',
           save_path: 'convolutional_network_best.pkl'
       },
    ],
    save_path: 'convolutional_network_live.pkl',
    save_freq: 1
}
