!obj:pylearn2.train.Train {
    
    dataset: &train !obj:friesnsteaks.datasets.food100.FOOD100 {
        which_set: 'train'
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:pylearn2.models.mlp.Sigmoid {
                     layer_name: 'h0',
                     dim: 50,
                     sparse_init: 5,
                 }, !obj:pylearn2.models.mlp.Sigmoid {
                     layer_name: 'y',
                     dim: 74,
                     sparse_init: 5,
                 }
                ],
        nvis: 49152,
    },
    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
        batch_size: 16800,
        line_search_mode: 'exhaustive',
        conjugate: 1,
        updates_per_batch: 10,
        monitoring_dataset:
            {
                'train' : *train,
                'test'  : !obj:friesnsteaks.datasets.food100.FOOD100 {
                              which_set: 'test',
                          }
            },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "test_objective"
                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 22 
                }
            ]
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'test_objective',
             save_path: "mlp_best.pkl"
        },
    ]
}
